[package]
name = "qruhear"
version = "0.1.1"
edition = "2021"
authors = ["michalwarda <mw@grifel.dev>"]
description = "A library for capturing audio from the system."
license = "Apache-2.0"

repository = "https://github.com/qforge-dev/qruhear"
documentation = "https://docs.rs/qruhear"
keywords = ["audio", "capture"]
categories = ["multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"

[target.'cfg(target_os = "macos")'.dependencies]
screencapturekit = "0.3"
core-foundation = "0.10"

[target.'cfg(not(target_os = "macos"))'.dependencies]
cpal = "0.15.2"

[[example]]
name = "capture"

[[example]]
name = "error"
